#!/usr/bin/python
import sys,socket,os

conn = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
host = "localhost"
port = 18888
bufferSize = 1024
conn.connect((host, port))
message = "lastdir"
conn.send(message)
data = conn.recv(bufferSize)
conn.close()
print data